# Generated by Django 5.2.5 on 2025-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
